### ISSUE TITLE
Why doesn't barge-pkg-openssl-2.10.0 contain /usr/bin/openssl?

### ISSUE THREAD

**Issue by diyism** [bargees/barge-os#104]
```
$sudo pkg install -f openssl -e BR2_PACKAGE_OPENSSL_BIN=y
...
Installing...
barge-pkg-openssl-2.10.0 has been installed into the system.
```

But I can't find /usr/bin/openssl, why?

**Comment by ailispaw** [comment]
According to https://github.com/buildroot/buildroot/blob/master/package/openssl/Config.in ,
It should be `BR2_PACKAGE_LIBOPENSSL_BIN` instead of `BR2_PACKAGE_OPENSSL_BIN`.

Please try with `-e BR2_PACKAGE_LIBOPENSSL_BIN=y`. Thank you.

PS:
Please open an issue regarding barge-pkg at https://github.com/bargees/barge-pkg next time.

**Comment by diyism** [comment]
Great, thanks
