### ISSUE TITLE
Customized Barge Vagrant box doesn't start without tricks

### ISSUE THREAD

**Issue by kaitoy** [bargees/barge-os#24]
I made a customized Vagrant box using Barge box as follows:

1. `vagrant init ailispaw/barge`
2. `vagrant up`
3. SSH to the VM and make some changes
4. `vagrant halt`
5. `vagrant package`

Then, I added the box and attempted to start it in the other PC:

1. `vagrant box add customized_barge package.box`
2. `vagrant init customized_barge`
3. `vagrant up`

But the `vagrant up` timed out due to unresponsive SSH.

I checked the VM state from VirtualBox GUI and found it was complaining that no bootable medium found.
So, I connected `%userprofile%\.vagrant.d\boxes\ailispaw-VAGRANTSLASH-barge\2.2.7.2\virtualbox\barge.iso` to the VM's SATA port and attempted `vagrant up` again.

It timed out due to another problem, SSH authentication failure.
After some investigation, I found I needed to add `config.ssh.username = "bargee"` to my Vagrantfile.

With the two fixes above, I finally could start the customized_barge.
Is this a proper way to create and use a custom barge box or is there an easier smarter way?

I used Vagant 1.8.6, VirtualBox 5.1.8, and Barge box 2.2.7.2 on Windows 7.

**Comment by ailispaw** [comment]
Hi @kaitoy,
Thank you for using Barge and opening the issue.

I use an another repo to create the box.
https://github.com/bargees/barge-packer/tree/master/virtualbox

As you have already pointed out, there are some special configuration in the box to use it properly.
You can find them here.
https://github.com/bargees/barge-packer/tree/master/virtualbox/box
Or you can find them in your local machine.
`%userprofile%\.vagrant.d\boxes\ailispaw-VAGRANTSLASH-barge\2.2.7.2\virtualbox\`

If you have Packer which is a tool to create a box from scratch, that would be the easiest way to do it.

**Comment by kaitoy** [comment]
I don't have Packer.
Why wasn't barge.iso packed into my  customized_barge?
I also found the Docker port 2375 is not exposed so I need to add a port forwarding configuration to my Vagrantfile for the customized_barge.
Are there anythings I have to do? Can you list up?

**Comment by ailispaw** [comment]
`vagrant package` packs only the HDD image in the VM folder by default.

You have to pack the following files from `%userprofile%\.vagrant.d\boxes\ailispaw-VAGRANTSLASH-barge\2.2.7.2\virtualbox\` with command options as well.
- Vagrantfile
- vagrant_plugin_guest_busybox.rb
- mount_virtualbox_shared_folder.rb
- mount_nfs.rb
- barge.iso

https://www.vagrantup.com/docs/cli/package.html

1. Make a working folder somewhere else from the current running Vagrant folder.
2. Copy the above files from `%userprofile%\.vagrant.d\boxes\ailispaw-VAGRANTSLASH-barge\2.2.7.2\virtualbox\` into the working folder.
  Note: The `Vagrantfile` is not yours, but from `%userprofile%\.vagrant.d\boxes\ailispaw-VAGRANTSLASH-barge\2.2.7.2\virtualbox\`.
3. Remove `~/.ssh` folder in the VM which you want to base a new box on, to SSH into new instances correctly,
because Vagrant has replaced it with new one for each VM on `vagrant up`.
4. Execute the following command.

```
$ vagrant package --base <the base VM name on VirtualBox> --include vagrant_plugin_guest_busybox.rb,mount_virtualbox_shared_folder.rb,mount_nfs.rb,barge.iso --vagrantfile Vagrantfile
$ vagrant box add -f customized_barge package.box
$ mkdir test
$ cd test
$ vagrant init -m customized_barge
$ vagrant up
```

**Comment by ailispaw** [comment]
BTW, I recommend you to use `config.vm.provision` in your Vagrantfile to customize the VM, and share the Vagrantfile with others. It is the easiest way.

**Comment by ailispaw** [comment]
You may need to remove the following files as well as `~/.ssh` before packaging.

- SSH host keys at `/etc/ssh`
- `/etc/dhcpcd.duid`
- `/etc/random-seed`

They are generated on the first boot automatically.

**Comment by kaitoy** [comment]
I followed your instructions and succeeded in adding and starting the customized box without any tricks.
Removing the following files wasn't needed:
> SSH host keys at /etc/ssh
> /etc/dhcpcd.duid
> /etc/random-seed

Thank you!
