### ISSUE TITLE
How to set registry-mirror params for docker in bargee?

### ISSUE THREAD

**Issue by JermineHu** [bargees/barge-os#55]
**First of all, thank you very much for barge-os provided by bargees !**
I use bargees in vagrant to use docker， In order to speed up,   I set up the docker registry-mirror as below picture, but it didn't work! Is there a problem with my configuration?

![qq 20171011152617](https://user-images.githubusercontent.com/18027793/31427460-f12ddd68-ae99-11e7-9881-da197729f7da.png)

**Comment by ailispaw** [comment]
@JermineHu 

Thank you for using Barge.

I set up as below to use a docker registry-mirror.

```
DOCKER_EXTRA_ARGS="--userland-proxy=false \
  --registry-mirror=http://<REGISTRY_IP/DOMAIN>:<PORT> \
  --insecure-registry=<REGISTRY_IP/DOMAIN>:<PORT>"
```

I guess that you need the `--insecure-registry` parameter to connect with no SSL mirror.

Oh, I found that you use `DOCKER_OPTS` instead of `DOCKER_EXTRA_ARGS`.

Please use `DOCKER_EXTRA_ARGS` for that.

Cf.) https://github.com/bargees/barge-os/blob/master/docs/customization.md#defaults

**Comment by JermineHu** [comment]
@ailispaw 

**Aha, I forgot to read the document! You solved my problem perfectly! Barge-OS is really great! Looking forward to the future of Barge-OS's dockerv17.09.0-ce!**

**Comment by ailispaw** [comment]
@JermineHu 

If you have Barge v2.6.1, you can upgrade Docker to v17.09.0-ce as usual.

```
$ sudo /etc/init.d/docker restart latest
# or
$ sudo /etc/init.d/docker restart v17.09.0-ce
```

**Comment by JermineHu** [comment]
@ailispaw  
**You truly are an amazing man! I've recommended your project to my circle of friends by wechat！I will continue to pay attention to your project and expect surprises! Ha-ha！**
